[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ai-sense"
version = "0.0.1"
authors = [
    {name = "Xingwei Wang", email = "wxwjkl123@gmail.com"},
]
description = "Implemented normal algorithms and neural network models and methods in AIoT"
requires-python = ">=3.7"
dependencies = [
    "numpy",

]

[project.urls]
"Homepage" = "https://github.com/xibrer/ai-sense"

# explicitly list the packages in modules
[tool.setuptools]
packages = ["ai_sense"]



