[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "senseport"
version = "0.0.2"
authors = [
    {name = "Xingwei Wang", email = "wxwjkl123@gmail.com"},
]
description = "Plug-and-Play modules in AI sensing can be inserted into your network"
requires-python = ">=3.7"
dependencies = [
    "numpy",

]

[project.urls]
"Homepage" = "https://github.com/xibrer/senseport"

# explicitly list the packages in modules
#[tool.setuptools]
#packages = ["senseport"]



