[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "torchsense"
version = "0.0.2"
authors = [
    {name = "Xingwei Wang", email = "wxwjkl123@gmail.com"},
]
description = "Torchsense is a library for sensor data processing with PyTorch"
requires-python = ">=3.7"
dependencies = [
    "numpy",

]

[project.urls]
"Homepage" = "https://github.com/xibrer/torchsense"

# explicitly list the packages in modules
#[tool.setuptools]
#packages = ["torchsense"]



